---
- name: prov servers
  hosts: all
  become: yes
  tasks:
    - name: Install NTP Agent on RHEL
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "RHEL"

    - name: Install NTP on Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Chronyd Service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "RHEL"

    - name: Start NTP Service
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"