---
- name: prov servers
  hosts: all
  become: yes
  tasks:
    - name: Install NTP Agent on RHEL
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "RHEL"

    - name: Install NTP on Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Chronyd Service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "RHEL"

    - name: Start NTP Service
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Copy Inline Content
      copy:
        content: "This Server is Managed by Gitansh"
        dest: /etc/motd

    - name: Deploy NTP Agent on RHEL
      template:
        src: template/RHEL_conf
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "RedHat"

    - name: Deploy NTP Agent on Ubuntu
      template:
        src: template/Ubuntu_conf
        dest: /etc/ntpsec/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"

    - name: Restart Chronyd Service
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "RHEL"

    - name: Restart NTP Service
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Create Folder
      file:
        path: /opt/t-zinga
        state: directory
        
    - name: Create a Folder
      file:
        path: 'opt/rimac21'
        state: "directory"
        mode: '0777'